[project]
name = "prometheus-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "buildtools>=1.0.6",
    "pip>=25.3",
    "psutil>=7.1.3",
]
